# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/CrossPlatformAudio/CrossPlatformAudio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/CrossPlatformAudio/CrossPlatformAudio/build-web

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/CrossPlatformAudio/CrossPlatformAudio/build-web/CMakeFiles /home/runner/work/CrossPlatformAudio/CrossPlatformAudio/build-web//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/CrossPlatformAudio/CrossPlatformAudio/build-web/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CrossPlatformAudio

# Build rule for target.
CrossPlatformAudio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CrossPlatformAudio
.PHONY : CrossPlatformAudio

# fast build rule for target.
CrossPlatformAudio/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CrossPlatformAudio.dir/build.make CMakeFiles/CrossPlatformAudio.dir/build
.PHONY : CrossPlatformAudio/fast

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CrossPlatformAudio.dir/build.make CMakeFiles/CrossPlatformAudio.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CrossPlatformAudio.dir/build.make CMakeFiles/CrossPlatformAudio.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CrossPlatformAudio.dir/build.make CMakeFiles/CrossPlatformAudio.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/WebAudioEngine.o: src/WebAudioEngine.cpp.o
.PHONY : src/WebAudioEngine.o

# target to build an object file
src/WebAudioEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CrossPlatformAudio.dir/build.make CMakeFiles/CrossPlatformAudio.dir/src/WebAudioEngine.cpp.o
.PHONY : src/WebAudioEngine.cpp.o

src/WebAudioEngine.i: src/WebAudioEngine.cpp.i
.PHONY : src/WebAudioEngine.i

# target to preprocess a source file
src/WebAudioEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CrossPlatformAudio.dir/build.make CMakeFiles/CrossPlatformAudio.dir/src/WebAudioEngine.cpp.i
.PHONY : src/WebAudioEngine.cpp.i

src/WebAudioEngine.s: src/WebAudioEngine.cpp.s
.PHONY : src/WebAudioEngine.s

# target to generate assembly for a file
src/WebAudioEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CrossPlatformAudio.dir/build.make CMakeFiles/CrossPlatformAudio.dir/src/WebAudioEngine.cpp.s
.PHONY : src/WebAudioEngine.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CrossPlatformAudio"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/WebAudioEngine.o"
	@echo "... src/WebAudioEngine.i"
	@echo "... src/WebAudioEngine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

