# Workflow for deploying to GitHub Pages.
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Grant the GITHUB_TOKEN the necessary permissions to create a deployment.
permissions:
  contents: read
  pages: write
  id-token: write

# Use a concurrency group to ensure that only one deployment happens at a time.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job 1: Build the project and upload the build artifacts.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: '3.1.55'
          cache-key: 'emsdk-cache'

      - name: Build WebAssembly project
        run: |
          mkdir -p build-web
          cd build-web
          emcmake cmake ..
          cmake --build .

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # This action packages the entire 'build-web' directory into a special zip file
      # called 'github-pages' that the 'deploy' job can access.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build-web'

  # Job 2: Deploy the uploaded artifact to GitHub Pages.
  deploy:
    # This job requires the 'build' job to have completed successfully.
    needs: build
    
    # The permissions are inherited from the top level.
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # This is the official action for deploying the artifact. It handles everything.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
